### ISSUE TITLE
Online tests failing

### ISSUE THREAD

**Issue by richmarr** [rgrove/node-elastical#11]
Hi there. I'm getting 11 failures in the online tests, this is with a clean `git clone` of https://github.com/rgrove/node-elastical/ and an otherwise apparently operational index running on http://localhost:9200.

```
✗ Broken » 28 honored ∙ 11 broken (0.425s)
```

Most of them seem to involve a TypeMissingException on the "_all" type, e.g.

```
  Client get() options.ignoreMissing when true and the document does not exist
    ✗ should not respond with an error
      » expected null, got {
    stack: 'Error: TypeMissingException[[elastical-test-get] type[_all] missing]
        at Error (unknown source)
        at Request._callback (/Users/richardmarr/Projects/node-elastical/lib/client.js:716:26)
        at Request.callback (/Users/richardmarr/Projects/node-elastical/node_modules/request/main.js:104:22)
        at Request.<anonymous> (/Users/richardmarr/Projects/node-elastical/node_modules/request/main.js:458:18)
        at Request.<anonymous> (events.js:64:17)
        at Request.emit (/Users/richardmarr/Projects/node-elastical/node_modules/vows/lib/vows.js:236:24)
        at IncomingMessage.<anonymous> (/Users/richardmarr/Projects/node-elastical/node_modules/request/main.js:423:16)
        at IncomingMessage.<anonymous> (events.js:81:20)
        at IncomingMessage.emit (/Users/richardmarr/Projects/node-elastical/node_modules/vows/lib/vows.js:236:24)
        at HTTPParser.onMessageComplete (http.js:133:23)',
    arguments: undefined,
    message: 'TypeMissingException[[elastical-test-get] type[_all] missing]',
    type: undefined
```

This may not actually be an issue that originates in `node-elastical`, but I thought I'd raise it here first in case you're aware of it.

**Comment by rgrove** [comment]
All tests are passing for me in ElasticSearch 0.18.6 on OS X. What version/platform are you using?

**Comment by richmarr** [comment]
Yeah, I'm thinking this is an ES issue. This is what these URLs return in the browser after having run the tests. 

http://localhost:9200/elastical-test-bulk/post/bar

```
 {"_index":"elastical-test-bulk","_type":"post","_id":"bar","_version":14, "_source" : {"c":"c","d":"d"}}
```

http://localhost:9200/elastical-test-bulk/_all/bar

```
 {"error":"TypeMissingException[[elastical-test-bulk] type[_all] missing]","status":404}
```

To my understanding the `_all` field should work. I'm on `0.16.1`. I didn't think `_all` was introduced more recently than that but this behaviour indicates it's either absent or disabled somehow. Suggest closing this issue for now.

**Comment by rgrove** [comment]
Hmm, yeah, that could be it. The oldest version I've tested with Elastical is 0.17.6 or so. It's possible older versions aren't compatible.

**Comment by richmarr** [comment]
Confirmed. Upgraded to `0.18.6`, ran teardown, then setup, then online-tests and everything passed.

**Comment by rgrove** [comment]
Cool, thanks for the followup.
