### ISSUE TITLE
Stack trace: <ClientRequest> has no method 'setTimeout'

### ISSUE THREAD

**Issue by richmarr** [rgrove/node-elastical#17]
I'm on Node 0.4.7, and Request 2.9.152 is being pulled in by Elastical, but this new version is failing.

TypeError: Object #<ClientRequest> has no method 'setTimeout'
     at Request.start (/app/node_modules/elastical/node_modules/request/main.js:475:14)
     at EventEmitter._tickCallback (node.js:126:26)
     at Request.write (/app/node_modules/elastical/node_modules/request/main.js:687:28)
     at Array.<anonymous> (/app/node_modules/elastical/node_modules/request/main.js:308:14)

Any ideas? Is this a Request bug?

**Comment by rgrove** [comment]
Definitely not an Elastical bug. Can you file an issue against Request?

https://github.com/mikeal/request/issues

**Comment by richmarr** [comment]
Filed, cheers.
