### ISSUE TITLE
Error: undefined is not a valid uri or options object. (breakage with request@2.9.200)

### ISSUE THREAD

**Issue by nyx** [rgrove/node-elastical#19]
I did a fresh npm install with elastical 0.0.7 and an updated request version was pulled down which seems to cause trouble.
Patching the package.json to specify request version "=2.9.1" addressed the issue.

Here's the stack trace I was seeing with request 2.9.2

```
Error: undefined is not a valid uri or options object.
    at request (project/node_modules/elastical/node_modules/request/main.js:786:41)
    at project/node_modules/elastical/node_modules/request/main.js:810:14
    at Object._request (project/node_modules/elastical/lib/client.js:713:9)
    at Object.search (project/node_modules/elastical/lib/client.js:530:14)
```

**Comment by rgrove** [comment]
Fixed in 0.0.8. Thanks for the report!
